In [2]:
import pandas as pd 

data = [1,2,3,4]
series = pd.Series(data) 
print(series)

0    1
1    2
2    3
3    4
dtype: int64

In [ ]:
#create series from dictionaries 

data = {'a':1,'b':2,'c':3}

dict_series= pd.Series(data)
print(dict_series)

a    1
b    2
c    3
dtype: int64

In [33]:
# creating series using the index and data 

data = [1,2,3]
index_values = ['a','b','c']

indexed_series = pd.Series(data,index=index_values)
print(indexed_series)

a    1
b    2
c    3
dtype: int64

In [8]:
#creating data frame using dictionary of list 
data = {
    "name":["krish","john","klark"],
    "age":[22,34,45],
    "city":["banglore","new york","florida"]
}

df = pd.DataFrame(data)
print(df)

    name  age      city
0  krish   22  banglore
1   john   34  new york
2  klark   45   florida

In [30]:
# creating the data frame using list of dictionaries 

data1 = [
    {"Name": "Sai", "Age": 22, "Marks": 97},
    {"Name": "Rahul", "Age": 21, "Marks": 90},
    {"Name": "Priya", "Age": 23, "Marks": 95}
]

list_of_dictionaries = pd.DataFrame(data1)
print(list_of_dictionaries)

    Name  Age  Marks
0    Sai   22     97
1  Rahul   21     90
2  Priya   23     95

In [13]:
# reading the csv file 
df = pd.read_csv("../../datasets/archive/CAvideos.csv")
# df = pd.read_csv("CAvideos.csv")

In [14]:
df.head(5)

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description
0,n1WpP7iowLc,17.14.11,Eminem - Walk On Water (Audio) ft. Beyoncé,EminemVEVO,10,2017-11-10T17:00:03.000Z,"Eminem|""Walk""|""On""|""Water""|""Aftermath/Shady/In...",17158579,787425,43420,125882,https://i.ytimg.com/vi/n1WpP7iowLc/default.jpg,False,False,False,Eminem's new track Walk on Water ft. Beyoncé i...
1,0dBIkQ4Mz1M,17.14.11,PLUSH - Bad Unboxing Fan Mail,iDubbbzTV,23,2017-11-13T17:00:00.000Z,"plush|""bad unboxing""|""unboxing""|""fan mail""|""id...",1014651,127794,1688,13030,https://i.ytimg.com/vi/0dBIkQ4Mz1M/default.jpg,False,False,False,STill got a lot of packages. Probably will las...
2,5qpjK5DgCt4,17.14.11,"Racist Superman | Rudy Mancuso, King Bach & Le...",Rudy Mancuso,23,2017-11-12T19:05:24.000Z,"racist superman|""rudy""|""mancuso""|""king""|""bach""...",3191434,146035,5339,8181,https://i.ytimg.com/vi/5qpjK5DgCt4/default.jpg,False,False,False,WATCH MY PREVIOUS VIDEO ▶ \n\nSUBSCRIBE ► http...
3,d380meD0W0M,17.14.11,I Dare You: GOING BALD!?,nigahiga,24,2017-11-12T18:01:41.000Z,"ryan|""higa""|""higatv""|""nigahiga""|""i dare you""|""...",2095828,132239,1989,17518,https://i.ytimg.com/vi/d380meD0W0M/default.jpg,False,False,False,I know it's been a while since we did this sho...
4,2Vv-BfVoq4g,17.14.11,Ed Sheeran - Perfect (Official Music Video),Ed Sheeran,10,2017-11-09T11:04:14.000Z,"edsheeran|""ed sheeran""|""acoustic""|""live""|""cove...",33523622,1634130,21082,85067,https://i.ytimg.com/vi/2Vv-BfVoq4g/default.jpg,False,False,False,🎧: https://ad.gt/yt-perfect\n💰: https://atlant...

In [12]:
df.tail(5)

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description
40876,sGolxsMSGfQ,18.14.06,HOW2: How to Solve a Mystery,Annoying Orange,24,2018-06-13T18:00:07.000Z,"annoying orange|""funny""|""fruit""|""talking""|""ani...",80685,1701,99,1312,https://i.ytimg.com/vi/sGolxsMSGfQ/default.jpg,False,False,False,🚨 NEW MERCH! http://amzn.to/annoyingorange 🚨➤ ...
40877,8HNuRNi8t70,18.14.06,Eli Lik Lik Episode 13 Partie 01,Elhiwar Ettounsi,24,2018-06-13T19:01:18.000Z,"hkayet tounsia|""elhiwar ettounsi""|""denya okhra...",103339,460,66,51,https://i.ytimg.com/vi/8HNuRNi8t70/default.jpg,False,False,False,► Retrouvez vos programmes préférés : https://...
40878,GWlKEM3m2EE,18.14.06,KINGDOM HEARTS III – SQUARE ENIX E3 SHOWCASE 2...,Kingdom Hearts,20,2018-06-11T17:30:53.000Z,"Kingdom Hearts|""KH3""|""Kingdom Hearts 3""|""Froze...",773347,25900,224,3881,https://i.ytimg.com/vi/GWlKEM3m2EE/default.jpg,False,False,False,Find out more about Kingdom Hearts 3: https://...
40879,lbMKLzQ4cNQ,18.14.06,Trump Advisor Grovels To Trudeau,The Young Turks,25,2018-06-13T04:00:05.000Z,"180612__TB02SorryExcuse|""News""|""Politics""|""The...",115225,2115,182,1672,https://i.ytimg.com/vi/lbMKLzQ4cNQ/default.jpg,False,False,False,Peter Navarro isn’t talking so tough now. Ana ...
40880,POTgw38-m58,18.14.06,【完整版】遇到恐怖情人該怎麼辦？2018.06.13小明星大跟班,我愛小明星大跟班,24,2018-06-13T16:00:03.000Z,"吳宗憲|""吳姍儒""|""小明星大跟班""|""Sandy""|""Jacky wu""|""憲哥""|""中天...",107392,300,62,251,https://i.ytimg.com/vi/POTgw38-m58/default.jpg,False,False,False,藝人：李妍瑾、玉兔、班傑、LaLa、小優、少少專家：陳筱屏(律師)、Wendy(心理師)、羅...

In [26]:
#accessing the column values
df['video_id']

0        n1WpP7iowLc
1        0dBIkQ4Mz1M
2        5qpjK5DgCt4
3        d380meD0W0M
4        2Vv-BfVoq4g
            ...
40876    sGolxsMSGfQ
40877    8HNuRNi8t70
40878    GWlKEM3m2EE
40879    lbMKLzQ4cNQ
40880    POTgw38-m58
Name: video_id, Length: 40881, dtype: str

In [ ]:
#accessing the rows 
df.loc[0]

video_id                                                        n1WpP7iowLc
trending_date                                                      17.14.11
title                            Eminem - Walk On Water (Audio) ft. Beyoncé
channel_title                                                    EminemVEVO
category_id                                                              10
publish_time                                       2017-11-10T17:00:03.000Z
tags                      Eminem|"Walk"|"On"|"Water"|"Aftermath/Shady/In...
views                                                              17158579
likes                                                                787425
dislikes                                                              43420
comment_count                                                        125882
thumbnail_link               https://i.ytimg.com/vi/n1WpP7iowLc/default.jpg
comments_disabled                                                     False
ratings_disabled                                                      False
video_error_or_removed                                                False
description               Eminem's new track Walk on Water ft. Beyoncé i...
Name: 0, dtype: object

In [ ]:
#accessing the values using row and column ( indexed loc )
df.iloc[0,0]

'n1WpP7iowLc'

In [40]:
#accessing the specific value

print(f"channel title of 1st row: {df.at[1,'channel_title']}")
print(f"views of the 3rd row :{df.at[3,'views']}")

channel title of 1st row: iDubbbzTV
views of the 3rd row :2095828

In [55]:
#adding the column 
list_of_dictionaries['salary']=[50000,60000,70000]
list_of_dictionaries

    Name  Age  Marks  salary
0    Sai   22     97   50000
1  Rahul   21     90   60000
2  Priya   23     95   70000

In [ ]:
# drop the column  

# axis = 0 ( rows )
# axis = 1 ( column )

list_of_dictionaries.drop('salary',axis=1,inplace=True)

C:\Users\saik3\AppData\Local\Temp\ipykernel_8472\3079681839.py:2: Pandas4Warning: The inplace keyword in DataFrame.drop is deprecated and will be removed in a future version (PDEP-8).
See https://pandas.pydata.org/docs/dev/whatsnew/v3.1.0.html#deprecation-inplace for more details.
  list_of_dictionaries.drop('salary',axis=1,inplace=True)

In [60]:
list_of_dictionaries

    Name  Age  Marks  salary
0    Sai   22     97   50000
1  Rahul   21     90   60000
2  Priya   23     95   70000

In [ ]:
# drop the row
list_of_dictionaries.drop(0,axis=0,inplace=True)

C:\Users\saik3\AppData\Local\Temp\ipykernel_8472\1982461694.py:1: Pandas4Warning: The inplace keyword in DataFrame.drop is deprecated and will be removed in a future version (PDEP-8).
See https://pandas.pydata.org/docs/dev/whatsnew/v3.1.0.html#deprecation-inplace for more details.
  list_of_dictionaries.drop(0,axis=0,inplace=True)

In [65]:
list_of_dictionaries

    Name  Age  Marks
1  Rahul   21     90
2  Priya   23     95

In [69]:
# opeartion on the data frame 

list_of_dictionaries['Age']= list_of_dictionaries['Age']+1
list_of_dictionaries

    Name  Age  Marks
1  Rahul   22     90
2  Priya   24     95

In [ ]:
# stastical analysis ( count , mean , std , min , max , )

df.describe()

        category_id         views         likes      dislikes  comment_count
count  40881.000000  4.088100e+04  4.088100e+04  4.088100e+04   4.088100e+04
mean      20.795553  1.147036e+06  3.958269e+04  2.009195e+03   5.042975e+03
std        6.775054  3.390913e+06  1.326895e+05  1.900837e+04   2.157902e+04
min        1.000000  7.330000e+02  0.000000e+00  0.000000e+00   0.000000e+00
25%       20.000000  1.439020e+05  2.191000e+03  9.900000e+01   4.170000e+02
50%       24.000000  3.712040e+05  8.780000e+03  3.030000e+02   1.301000e+03
75%       24.000000  9.633020e+05  2.871700e+04  9.500000e+02   3.713000e+03
max       43.000000  1.378431e+08  5.053338e+06  1.602383e+06   1.114800e+06