### read_json(StringIo(data))
### dataframe to_json(orient='records')

### read_csv(url,header=None) 
### dataframe to_csv(filename)

### read_html(url,match=column table from table)

### read_excel(excel sheet name)

In [ ]:
#converting json to data frames

import pandas as pd 
from io import StringIO

data  = '{"employee_name":"saikiran", "email":"skrnpuppal@gmail.com", "job_profile": [{"title":"teamlead", "title2":"sr developer"}]}'
df = pd.read_json(StringIO(data))

In [2]:
df

,employee_name,email,job_profile
0,saikiran,skrnpuppal@gmail.com,"{'title': 'teamlead', 'title2': 'sr developer'}"

In [3]:
print(type(df))

<class 'pandas.DataFrame'>

In [11]:
#converting data frame to json 

json_format = df.to_json(orient="records")
json_format

'[{"employee_name":"saikiran","email":"skrnpuppal@gmail.com","job_profile":{"title":"teamlead","title2":"sr developer"}}]'

In [13]:
print(type(json_format))

<class 'str'>

In [15]:
# reading the csv file using read_csv 
#converting the csv format to data frame

url = "https://archive.ics.uci.edu/ml/machine-learning-databases/wine/wine.data"
df1 = pd.read_csv(url,header=None)
df1

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
0,1,14.23,1.71,2.43,15.6,127,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065
1,1,13.20,1.78,2.14,11.2,100,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050
2,1,13.16,2.36,2.67,18.6,101,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185
3,1,14.37,1.95,2.50,16.8,113,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480
4,1,13.24,2.59,2.87,21.0,118,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
173,3,13.71,5.65,2.45,20.5,95,1.68,0.61,0.52,1.06,7.70,0.64,1.74,740
174,3,13.40,3.91,2.48,23.0,102,1.80,0.75,0.43,1.41,7.30,0.70,1.56,750
175,3,13.27,4.28,2.26,20.0,120,1.59,0.69,0.43,1.35,10.20,0.59,1.56,835
176,3,13.17,2.59,2.37,20.0,120,1.65,0.68,0.53,1.46,9.30,0.60,1.62,840
177,3,14.13,4.10,2.74,24.5,96,2.05,0.76,0.56,1.35,9.20,0.61,1.60,560

In [ ]:
# converting the data frame to csv 

df3 = df.to_csv('wine.csv')

In [22]:
# reading the tables from html pages 

url1 = "https://www.fdic.gov/bank-failures/failed-bank-list"
df4 = pd.read_html(url1)
df4
df4[0]

,Bank Name,City,State,Cert,Acquiring Institution,Closing Date,Fund Sort ascending
0,Nano Banc,Irvine,California,58590,Sunwest Bank,"September 25, 2026",10555
1,Tioga-Franklin Savings Bank,Philadelphia,Pennsylvania,33802,Second Federal Savings and Loan Association of...,"August 21, 2026",10554
2,Small Business Bank,Lenexa,Kansas,25744,"The Farmers State Bank of Oakley, Kansas","July 17, 2026",10553
3,Kentland Federal Savings and Loan Association,Kentland,Indiana,28722,Kentland Bank,"July 10, 2026",10552
4,Community Bank and Trust - West Georgia,LaGrange,Georgia,25796,Anchor Bank,"May 1, 2026",10551
5,Metropolitan Capital Bank & Trust,Chicago,Illinois,57488,First Independence Bank,"January 30, 2026",10550
6,The Santa Anna National Bank,Santa Anna,Texas,5520,Coleman County State Bank,"June 27, 2025",10549
7,Pulaski Savings Bank,Chicago,Illinois,28611,Millennium Bank,"January 17, 2025",10548
8,The First National Bank of Lindsay,Lindsay,Oklahoma,4134,First Bank & Trust Co.,"October 18, 2024",10547
9,Republic First Bank dba Republic Bank,Philadelphia,Pennsylvania,27332,"Fulton Bank, National Association","April 26, 2024",10546
10,Citizens Bank,Sac City,Iowa,8758,Iowa Trust & Savings Bank,"November 3, 2023",10545
11,Heartland Tri-State Bank,Elkhart,Kansas,25851,"Dream First Bank, N.A.","July 28, 2023",10544
12,First Republic Bank,San Francisco,California,59017,"JPMorgan Chase Bank, N.A.","May 1, 2023",10543
13,Signature Bank,New York,New York,57053,"Flagstar Bank, N.A.","March 12, 2023",10540
14,Silicon Valley Bank,Santa Clara,California,24735,First–Citizens Bank & Trust Company,"March 10, 2023",10539
15,Almena State Bank,Almena,Kansas,15426,Equity Bank,"October 23, 2020",10538
16,First City Bank of Florida,Fort Walton Beach,Florida,16748,"United Fidelity Bank, fsb","October 16, 2020",10537
17,The First State Bank,Barboursville,West Virginia,14361,"MVB Bank, Inc.","April 3, 2020",10536
18,Ericson State Bank,Ericson,Nebraska,18265,Farmers and Merchants Bank,"February 14, 2020",10535
19,City National Bank of New Jersey,Newark,New Jersey,21111,Industrial Bank,"November 1, 2019",10534
20,Resolute Bank,Maumee,Ohio,58317,Buckeye State Bank,"October 25, 2019",10533
21,Louisa Community Bank,Louisa,Kentucky,58112,Kentucky Farmers Bank Corporation,"October 25, 2019",10532
22,The Enloe State Bank,Cooper,Texas,10716,"Legend Bank, N. A.","May 31, 2019",10531
23,Washington Federal Bank for Savings,Chicago,Illinois,30570,Royal Savings Bank,"December 15, 2017",10530
24,The Farmers and Merchants State Bank of Argonia,Argonia,Kansas,17719,Conway Bank,"October 13, 2017",10529

In [68]:
# if pandas request is having some issue then use the requests lib and use the headers ( mozilla/5.0) 

import requests 
from io import StringIO

# url3 = "https://www.fdic.gov/bank-failures/failed-bank-list"

url3 = "https://en.wikipedia.org/wiki/Mobile_country_code"

headers = {
    "user-agent" : "mozilla/5.0"
}


response = requests.get(url3,timeout=20,headers=headers)

print(response.status_code)

df6 = pd.read_html(StringIO(response.text),match="country")

df6[0]

<class 'requests.models.Response'>
200

,Mobile country code,Country,ISO 3166,Mobile network codes,National MNC authority,Remarks
0,289,A Abkhazia,GE-AB,List of mobile network codes in Abkhazia,NaN,MCC is not listed by ITU
1,412,Afghanistan,AF,List of mobile network codes in Afghanistan,NaN,NaN
2,276,Albania,AL,List of mobile network codes in Albania,NaN,NaN
3,603,Algeria,DZ,List of mobile network codes in Algeria,NaN,NaN
4,544,American Samoa (United States of America),AS,List of mobile network codes in American Samoa,NaN,NaN
...,...,...,...,...,...,...
247,452,Vietnam,VN,List of mobile network codes in the Vietnam,NaN,NaN
248,543,W Wallis and Futuna,WF,List of mobile network codes in Wallis and Futuna,NaN,NaN
249,421,Y Yemen,YE,List of mobile network codes in the Yemen,NaN,NaN
250,645,Z Zambia,ZM,List of mobile network codes in Zambia,NaN,NaN
251,648,Zimbabwe,ZW,List of mobile network codes in Zimbabwe,NaN,NaN

In [69]:
# reading the data from excel sheet 

# openpyxl is required for reading the excel sheet 

df7 = pd.read_excel('data.xlsx')
df7

       name   age
0  saikiran     23
1    chanlee    24
2     obito     25

In [71]:
# pickles are usefull when you want to save the data permanently 
#when you close the python it forgets the data this pickle helps with that issue 


df7.to_pickle('pickle_df7.pkl')

In [72]:
# converting back the pickle file to data frame 

excel_df = pd.read_pickle("pickle_df7.pkl")
excel_df

       name   age
0  saikiran     23
1    chanlee    24
2     obito     25